<a href="https://colab.research.google.com/github/Brousigma/M1_Projet_DS/blob/main/Projet_IA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# importation des bibliothèques

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from io import StringIO
import plotly.express as px
import plotly.graph_objects as go
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor, plot_tree
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_squared_error
import statsmodels.api as sm
from sklearn.inspection import partial_dependence, PartialDependenceDisplay
import time

# For missing values visualization
!pip install missingno
import missingno as msno

# For outlier detection
!pip install pyod
from pyod.models.iforest import IForest

# For QQ plot data calculation
from scipy.stats import stats
# Step 0: Create and Load Dataset

Requirement already satisfied: missingno in /usr/local/lib/python3.10/dist-packages (0.5.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from missingno) (1.26.4)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.10/dist-packages (from missingno) (3.8.0)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from missingno) (1.13.1)
Requirement already satisfied: seaborn in /usr/local/lib/python3.10/dist-packages (from missingno) (0.13.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->missingno) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib->missingno) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->missingno) (4.55.3)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->missingno) (1.4.7)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->missingno) (24.2)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->missingno) (11.0.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->missingno) (3.2.0)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib->missingno) (2.8.2)
Requirement already satisfied: pandas>=1.2 in /usr/local/lib/python3.10/dist-packages (from seaborn->missingno) (2.2.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.2->seaborn->missingno) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.2->seaborn->missingno) (2024.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.7->matplotlib->missingno) (1.17.0)
Collecting pyod
  Downloading pyod-2.0.2.tar.gz (165 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 165.8/165.8 kB 9.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: joblib in /usr/local/lib/python3.10/dist-packages (from pyod) (1.4.2)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.10/dist-packages (from pyod) (3.8.0)
Requirement already satisfied: numpy>=1.19 in /usr/local/lib/python3.10/dist-packages (from pyod) (1.26.4)
Requirement already satisfied: numba>=0.51 in /usr/local/lib/python3.10/dist-packages (from pyod) (0.60.0)
Requirement already satisfied: scipy>=1.5.1 in /usr/local/lib/python3.10/dist-packages (from pyod) (1.13.1)
Requirement already satisfied: scikit-learn>=0.22.0 in /usr/local/lib/python3.10/dist-packages (from pyod) (1.6.0)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.10/dist-packages (from numba>=0.51->pyod) (0.43.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.22.0->pyod) (3.5.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->pyod) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib->pyod) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->pyod) (4.55.3)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->pyod) (1.4.7)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->pyod) (24.2)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->pyod) (11.0.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->pyod) (3.2.0)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib->pyod) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.7->matplotlib->pyod) (1.17.0)
Building wheels for collected packages: pyod
  Building wheel for pyod (setup.py) ... done
  Created wheel for pyod: filename=pyod-2.0.2-py3-none-any.whl size=198469 sha256=ab36c2773a43fb594257e1e953e4a05762389941d792ce2f62fc8c2f44fbd8f9
  Stored in directory: /root/.cache/pip/wheels/77/c2/20/34d1f15b41b701ba69f42a32304825810d680754d509f91391
Successfully built pyod
Installing collected packages: pyod
Successfully installed pyod-2.0.2

In [ ]:

# ça devrait normalement fonctionner

In [ ]:
# Okay je l'espère

In [ ]:
# Monter Google Drive
from google.colab import drive
drive.mount('/content/drive')

# importation du fichier excel train_etu en dataframe
df=pd.read_excel("/content/drive/My Drive/train_etu.xls")
df

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

,Identifiant,date_accident,date_communication,age,sexe,status_marital,enfants,autre_dep,salaire_semaine,patrimoine,type_emploi,heure_par_semaine,jour_par_semaine,description,cout_init,cout_ultime
0,W0000001,2002-04-09T07:00:00Z,2002-07-05T00:00:00Z,48,M,M,0,0,500.00,42938.0,F,38.0,5,LIFTING TYRE INJURY TO RIGHT ARM AND WRIST INJURY,1500,4748.203388
1,W0000002,1999-01-07T11:00:00Z,1999-01-20T00:00:00Z,43,F,M,0,0,509.34,415347.0,F,37.5,5,STEPPED AROUND CRATES AND TRUCK TRAY FRACTURE ...,5500,6326.285819
2,W0000003,1996-03-25T00:00:00Z,1996-04-14T00:00:00Z,30,M,U,0,0,709.10,1655066.0,F,38.0,5,CUT ON SHARP EDGE CUT LEFT THUMB,1700,2293.949087
3,W0000004,2005-06-22T13:00:00Z,2005-07-22T00:00:00Z,41,M,S,0,0,555.46,7507555.0,F,38.0,5,DIGGING LOWER BACK LOWER BACK STRAIN,15000,17786.487170
4,W0000005,1990-08-29T08:00:00Z,1990-09-27T00:00:00Z,36,M,M,0,0,377.10,293251.0,F,38.0,5,REACHING ABOVE SHOULDER LEVEL ACUTE MUSCLE STR...,2800,4014.002925
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45667,W0045668,1994-08-12T11:00:00Z,1994-09-15T00:00:00Z,50,M,M,2,0,696.05,NaN,F,38.0,5,LIFTING BACK STRAIN LOWER BACK STRAIN,11500,9785.507185
45668,W0045669,1996-11-21T14:00:00Z,1997-01-25T00:00:00Z,32,M,S,0,0,200.00,NaN,F,38.0,5,STRUCK STOVE LACERATION RIGHT LOWER FOREARM,1000,440.635652
45669,W0045670,1989-03-14T09:00:00Z,1989-04-11T00:00:00Z,30,M,S,0,0,615.38,NaN,F,38.0,5,FELL DOWN ON KNEE LEFT KNEE INJURY SWOLLEN,1500,12391.392090
45670,W0045671,2004-09-22T15:00:00Z,2004-10-02T00:00:00Z,40,M,S,2,0,561.26,NaN,F,38.0,5,LIFTED NETBALL HOOP NECK NECK STRAIN,9500,8483.748442
45671,W0045672,1998-09-29T10:00:00Z,1998-11-05T00:00:00Z,30,M,S,0,0,200.00,NaN,F,38.0,5,STRUCK METAL FROM SCREW GUN LACERATION LEFT MI...,500,226.716683

In [ ]:
# oui je vois oui je vois aussi

In [ ]:
# Chargement de la colonne description

df.description

0        LIFTING TYRE INJURY TO RIGHT ARM AND WRIST INJURY
1        STEPPED AROUND CRATES AND TRUCK TRAY FRACTURE ...
2                         CUT ON SHARP EDGE CUT LEFT THUMB
3                     DIGGING LOWER BACK LOWER BACK STRAIN
4        REACHING ABOVE SHOULDER LEVEL ACUTE MUSCLE STR...
                               ...
45667                LIFTING BACK STRAIN LOWER BACK STRAIN
45668          STRUCK STOVE LACERATION RIGHT LOWER FOREARM
45669           FELL DOWN ON KNEE LEFT KNEE INJURY SWOLLEN
45670                 LIFTED NETBALL HOOP NECK NECK STRAIN
45671    STRUCK METAL FROM SCREW GUN LACERATION LEFT MI...
Name: description, Length: 45672, dtype: object

 Remarquons que cette variable décrit le mouvemenr qui a conduit à la blessure ainsi que les parties du corps blessées